version: "3"
name: jenkins-compse


services:
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
        - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./data:/var/jenkins_home
      - ./certs:/certs/client
    ports:
      - "2376:2376"
      
      ## port app
      - "2929:8080"
      - "2204:3306"

  jenkins:
    container_name: jenkins
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: duncannguyen/jenkins
    ports:
      - "9090:8080"
      - "5000:5000"
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

    volumes:
      - ./data:/var/jenkins_home
      - ./certs:/certs/client

networks:
  jenkins:
  
